USE [AnyDoDB]
GO

/****** Object:  Table [dbo].[Note]    Script Date: 01.08.2016 11:11:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Note](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[TaskId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[Note]  WITH NOCHECK ADD  CONSTRAINT [FK_Note_MyTask] FOREIGN KEY([TaskId])
REFERENCES [dbo].[MyTask] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[Note] CHECK CONSTRAINT [FK_Note_MyTask]
GO

