USE [AnyDoDB]
GO

/****** Object:  Table [dbo].[UploadFile]    Script Date: 01.08.2016 11:12:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UploadFile](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FileName] [varchar](100) NOT NULL,
	[FilePath] [varchar](100) NOT NULL,
	[FileSize] [int] NOT NULL,
	[TaskId] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[UploadFile]  WITH NOCHECK ADD  CONSTRAINT [FK_UploadFile_MyTask] FOREIGN KEY([TaskId])
REFERENCES [dbo].[MyTask] ([Id])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[UploadFile] CHECK CONSTRAINT [FK_UploadFile_MyTask]
GO

