//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAnyDo2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubTask
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> TaskId { get; set; }
    
        public virtual MyTask MyTask { get; set; }
    }
}
